name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install dpkg coreutils xz ldid

      - name: Build tweak
        run: bash macos-build.sh

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: SwipeBackBkey
          path: ./*.deb
          if-no-files-found: error
